name: iadvancedscout
description: IAdvanced Scout

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  #BBDDD
  #firebase_core: ^0.7.0
  #firebase_auth: ^0.20.1
  firebase_core: ^0.5.1
  #cloud_firestore: ^0.14.2
  firebase_auth: ^0.18.2
  firebase_database: ^4.1.1
  firebase_storage: ^5.0.0
  flutter_signin_button: ^1.0.0

  #EXCEL
  gsheets: ^0.2.6
  #CVS
  csv: ^4.1.0

  provider: ^3.1.0

  pdf: ^1.5.0
  syncfusion_flutter_pdf: ^18.3.53-beta
  flutter_full_pdf_viewer: ^1.0.6


  flutter_html: ^0.8.2
  open_file: ^3.0.3
  url_launcher: ^5.7.10
  avatar_glow: ^1.2.0
  toggle_switch: ^0.1.8
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+14
  splashscreen : 1.2.0
  shared_preferences: ^0.5.12+4
  flutter_launcher_icons: ^0.8.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0

  sqflite:
  path_provider: ^0.4.1


flutter_icons:
  image_path: "assets/img/icono.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family:  CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf

  assets:
    - assets/pais/ESPAÑA.png
    - assets/pais/ALEMANIA.png
    - assets/pais/ARGENTINA.png
    - assets/pais/ESPANA.png
    - assets/pais/FRANCIA.png
    - assets/pais/PORTUGAL.png
    - assets/pais/URUGUAY.png
    - assets/pais/ITALIA.png
    - assets/img/camponegro.jpg
    - assets/img/campoblanco.png

    - assets/img/ia_logotipo.png
    - assets/img/123.png
    - assets/img/ok.png
    - assets/img/false.png
    - assets/img/lateralderecho.png
    - assets/img/carrileroderecho.png
    - assets/img/carrileroizquierdo.png
    - assets/img/central.png
    - assets/img/defensacentral.png
    - assets/img/centralderecho.png
    - assets/img/centralizquierdo.png
    - assets/img/delantero.png
    - assets/img/delanterocentro.png
    - assets/img/extremoderecho.png
    - assets/img/extremoizquierdo.png
    - assets/img/interiorderecho.png
    - assets/img/lateralderecho.png
    - assets/img/lateralizquierdo.png
    - assets/img/interiorizquierdo.png
    - assets/img/volantederecho.png
    - assets/img/volanteizquierdo.png
    - assets/img/pivote.png
    - assets/img/mediocentro.png
    - assets/img/mediocentroofensivo.png
    - assets/img/portero.png
    - assets/img/mediapunta.png
    - assets/img/mediocentroderecho.png
    - assets/img/mediocentroizquierdo.png
    - assets/pais/PORTUGAL.png
    - assets/img/fondo.png
    - assets/img/appbar.png
    - assets/img/icono.png
    - assets/img/iconotitulo.png
    - assets/img/campo.jpg
    - assets/img/1.png
    - assets/img/2.png
    - assets/img/47.png

    #clubes
    - assets/clubes/Albacete.png
    - assets/clubes/Alcorcón.png
    - assets/clubes/Cartagena.png
    - assets/clubes/Castellón.png
    - assets/clubes/Espanyol.png
    - assets/clubes/Fuenlabrada.png
    - assets/clubes/Girona.png
    - assets/clubes/Las Palmas.png
    - assets/clubes/Leganés.png
    - assets/clubes/Lugo.png
    - assets/clubes/Mallorca.png
    - assets/clubes/Mirandés.png
    - assets/clubes/Málaga.png
    - assets/clubes/Ponferradina.png
    - assets/clubes/Rayo Vallecano.png
    - assets/clubes/Real Oviedo.png
    - assets/clubes/Real Zaragoza.png
    - assets/clubes/Sabadell.png
    - assets/clubes/Sporting Gijón .png
    - assets/clubes/Tenerife.png
    - assets/clubes/UD Logroñés.png
    - assets/clubes/Almería.png

    - assets/clubes/Alcoyano.png
    - assets/clubes/Algeciras.png
    - assets/clubes/Amorebieta.png
    - assets/clubes/Arenas de Getxo.png
    - assets/clubes/Athletic Bilbao B.png
    - assets/clubes/Atlético Baleares.png
    - assets/clubes/Atlético Levante.png
    - assets/clubes/Atlético Madrid B.png
    - assets/clubes/Atlético Sanluqueño.png
    - assets/clubes/Atzeneta.png
    - assets/clubes/Badalona.png
    - assets/clubes/Barakaldo.png
    - assets/clubes/Barcelona B.png
    - assets/clubes/Burgos.png
    - assets/clubes/CD Badajoz.png
    - assets/clubes/CD Calahorra.png
    - assets/clubes/CD San Fernando.png
    - assets/clubes/Celta de Vigo B.png
    - assets/clubes/Compostela.png
    - assets/clubes/Cornellà.png
    - assets/clubes/Coruxo.png
    - assets/clubes/Covadonga.png
    - assets/clubes/Cultural Leonesa.png
    - assets/clubes/Cádiz B.png
    - assets/clubes/Córdoba.png
    - assets/clubes/Deportivo Alavés B.png
    - assets/clubes/Deportivo La Coruña.png
    - assets/clubes/Don Benito.png
    - assets/clubes/Ebro.png
    - assets/clubes/Ejea.png
    - assets/clubes/El Ejido.png
    - assets/clubes/Espanyol B.png
    - assets/clubes/Extremadura UD.png
    - assets/clubes/FC Andorra.png
    - assets/clubes/Getafe B.png
    - assets/clubes/Gimnàstic Tarragona.png
    - assets/clubes/Granada B.png
    - assets/clubes/Guijuelo.png
    - assets/clubes/Haro.png
    - assets/clubes/Hércules.png
    - assets/clubes/Internacional Madrid.png
    - assets/clubes/Izarra.png
    - assets/clubes/L Hospitalet.png
    - assets/clubes/La Nucía.png
    - assets/clubes/Langreo.png
    - assets/clubes/Laredo.png
    - assets/clubes/Las Palmas B.png
    - assets/clubes/Las Rozas.png
    - assets/clubes/Lealtad.png
    - assets/clubes/Leioa.png
    - assets/clubes/Linares Deportivo.png
    - assets/clubes/Linense.png
    - assets/clubes/Llagostera.png
    - assets/clubes/Lleida Esportiu.png
    - assets/clubes/Lorca Deportiva.png
    - assets/clubes/Marbella.png
    - assets/clubes/Marino.png
    - assets/clubes/Marino de Luanco.png
    - assets/clubes/Melilla.png
    - assets/clubes/Mutilvera.png
    - assets/clubes/Mérida AD.png
    - assets/clubes/Navalcarnero.png
    - assets/clubes/Numancia.png
    - assets/clubes/Olot.png
    - assets/clubes/Orihuela.png
    - assets/clubes/Osasuna B.png
    - assets/clubes/Peña Deportiva.png
    - assets/clubes/Poblense.png
    - assets/clubes/Pontevedra.png
    - assets/clubes/Portugalete.png
    - assets/clubes/Prat.png
    - assets/clubes/Racing Ferrol.png
    - assets/clubes/Racing Santander.png
    - assets/clubes/Rayo Majadahonda.png
    - assets/clubes/Real Betis B.png
    - assets/clubes/Real Madrid Castilla.png
    - assets/clubes/Real Murcia.png
    - assets/clubes/Real Oviedo B.png
    - assets/clubes/Real Sociedad B.png
    - assets/clubes/Real Unión.png
    - assets/clubes/Real Valladolid B.png
    - assets/clubes/Recreativo Huelva.png
    - assets/clubes/res Deportivo.png
    - assets/clubes/Salamanca CF UDS.png
    - assets/clubes/SD Logroñés.png
    - assets/clubes/Sevilla Atlético.png
    - assets/clubes/Socuéllamos.png
    - assets/clubes/Sporting Gijón B.png
    - assets/clubes/Sporting Gijón .png
    - assets/clubes/Sporting Gijón.png
    - assets/clubes/Talavera CF.png
    - assets/clubes/Tamaraceite.png
    - assets/clubes/Tarazona.png
    - assets/clubes/Tudelano.png
    - assets/clubes/UCAM Murcia.png
    - assets/clubes/UD Ibiza.png
    - assets/clubes/UD Sanse.png
    - assets/clubes/Unionistas de Salamanca.png
    - assets/clubes/Valencia B.png
    - assets/clubes/Villanovense.png
    - assets/clubes/Villarreal B.png
    - assets/clubes/Villarrobledo.png
    - assets/clubes/Villarrubia.png
    - assets/clubes/Yeclano.png
    - assets/clubes/Zamora.png
    - assets/Burgos/Claudio Medina.png
    - assets/Burgos/Eneko Undabarrena.png
    - assets/Burgos/Galder Cerrajería.png
    - assets/Burgos/Guillermo Fernández.png
    - assets/Burgos/Javi Gómez.png
    - assets/Burgos/Juanma Garcia.png
    - assets/Burgos/L. Pisculichi.png
    - assets/Burgos/M. Barovero.png
    - assets/Burgos/Miki Muñoz.png
    - assets/Burgos/Míchel Zabaco.png
    - assets/Burgos/R. Leak.png
    - assets/Burgos/Raúl Navarro.png
    - assets/Burgos/Roberto Alarcón.png
    - assets/Burgos/Rubén Lobato.png
    - assets/Burgos/Saúl Berjón.png
    - assets/Burgos/sinfoto.png
    - assets/Burgos/Unai Elgezabal.png
    - assets/Burgos/Álvaro Rodríguez.png
    - assets/img/jugador.png
    - assets/img/2b.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
