name: iadvancedscout
description: IAdvanced Scout

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  #BBDDD
  #firebase_core: ^0.7.0
  #firebase_auth: ^0.20.1
  firebase_core: ^0.5.1
  cloud_firestore: ^0.14.2
  firebase_auth: ^0.18.2
  firebase_database: ^4.1.1
  firebase_storage: ^5.0.0
  flutter_signin_button: ^1.0.0

  #EXCEL
  gsheets: ^0.2.6

  provider: ^3.1.0

  pdf: ^2.0.0
  syncfusion_flutter_pdf: ^18.3.53-beta
  flutter_full_pdf_viewer: ^1.0.6


  flutter_html: ^0.8.2
  open_file: ^3.0.3
  url_launcher: ^5.7.10
  avatar_glow: ^1.2.0
  toggle_switch: ^0.1.8
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+14
  splashscreen: 1.2.0
  #shared_preferences: ^0.5.12+4
  flutter_launcher_icons: ^0.8.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0

  sqflite:
  path_provider: ^1.6.28

  fluttertoast: ^4.0.0
  native_pdf_renderer: ^2.4.0
  image_gallery_saver: ^1.6.8
  #notificacionesx
  #firebase_messaging: ^7.0.3
  fluttericon: ^1.0.7

flutter_icons:
  image_path: "assets/img/icono.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family:  CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf
    - family:  IconMio
      fonts:
        - asset: fonts/IconMio.ttf
    - family:  FutbolMio
      fonts:
        - asset: fonts/FutbolMio.ttf


  assets:
    - assets/pais/ESPAÑA.png
    - assets/pais/ALEMANIA.png
    - assets/pais/ARGENTINA.png
    - assets/pais/ESPANA.png
    - assets/pais/FRANCIA.png
    - assets/pais/PORTUGAL.png
    - assets/pais/URUGUAY.png
    - assets/pais/ITALIA.png
    - assets/img/camponegro.jpg
    - assets/img/campoblanco.png

    - assets/img/ia_logotipo.png
    - assets/img/123.png
    - assets/img/ok.png
    - assets/img/false.png
    - assets/img/lateralderecho.png
    - assets/img/carrileroderecho.png
    - assets/img/carrileroizquierdo.png
    - assets/img/central.png
    - assets/img/defensacentral.png
    - assets/img/centralderecho.png
    - assets/img/centralizquierdo.png
    - assets/img/delantero.png
    - assets/img/delanterocentro.png
    - assets/img/extremoderecho.png
    - assets/img/extremoizquierdo.png
    - assets/img/interiorderecho.png
    - assets/img/lateralderecho.png
    - assets/img/lateralizquierdo.png
    - assets/img/interiorizquierdo.png
    - assets/img/volantederecho.png
    - assets/img/volanteizquierdo.png
    - assets/img/pivote.png
    - assets/img/mediocentro.png
    - assets/img/mediocentroofensivo.png
    - assets/img/portero.png
    - assets/img/mediapunta.png
    - assets/img/mediocentroderecho.png
    - assets/img/mediocentroizquierdo.png
    - assets/pais/PORTUGAL.png
    - assets/img/fondo.png
    - assets/img/appbar.png
    - assets/img/icono.png
    - assets/img/iconotitulo.png
    - assets/img/campo.jpg
    - assets/img/1.png
    - assets/img/2.png
    - assets/img/47.png

    #clubes
    - assets/Burgos/Claudio Medina.png
    - assets/Burgos/Eneko Undabarrena.png
    - assets/Burgos/Galder Cerrajería.png
    - assets/Burgos/Guillermo Fernández.png
    - assets/Burgos/Javi Gómez.png
    - assets/Burgos/Juanma Garcia.png
    - assets/Burgos/L. Pisculichi.png
    - assets/Burgos/M. Barovero.png
    - assets/Burgos/Miki Muñoz.png
    - assets/Burgos/Míchel Zabaco.png
    - assets/Burgos/R. Leak.png
    - assets/Burgos/Raúl Navarro.png
    - assets/Burgos/Roberto Alarcón.png
    - assets/Burgos/Rubén Lobato.png
    - assets/Burgos/Saúl Berjón.png
    - assets/Burgos/sinfoto.png
    - assets/Burgos/Unai Elgezabal.png
    - assets/Burgos/Álvaro Rodríguez.png
    - assets/img/jugador.png
    - assets/img/2b.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
