/// Flutter icons FutbolMio
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FutbolMio
///      fonts:
///       - asset: fonts/FutbolMio.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FutbolMio {
  FutbolMio._();

  static const _kFontFam = 'FutbolMio';
  static const Null _kFontPkg = null;

  static const IconData entrenador_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entrenador_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sustituir = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tactica_2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tactica_3 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tactica = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tactico = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tarjeta_amarilla = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
